version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"      # Use DB_PORT env var here
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db              # inside docker, hostname is service name
      DB_PORT: "5432"          # Postgres default port inside container
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    command: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pg_data:
